### ISSUE TITLE
400 error trying to follow mastodon users

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/fedireads#1]

**Comment by thricedotted** [comment]
Through sheer brute force, and absolutely no thanks to any cleverness, I think I figured this one out.

In `sign_and_send`, you explicitly set the `Host` header here:
https://github.com/mouse-reeve/fedireads/blob/master/fedireads/broadcast.py#L82

But something else is also trying to set `Host`! And according to MDN...

> A 400 (Bad Request) status code will be sent to any HTTP/1.1 request message that lacks a Host header field or contains more than one.

Commenting out that line and then trying to follow an external account leads to a 401 Unauthorized for Mastodon, and... a long hang for the [AP tester](https://glitch.com/~dariusk-aptester), which doesn't do any signature verification, so it's getting hung up on something else.

So, other things down the pipeline are still wonky, but at least they're not totally opaque 400 errors 
🤷

**Comment by mouse-reeve** [comment]
you are my HERO @thricedotted, I even think I know how to resolve the 401

**Comment by thricedotted** [comment]
🥳

You may already know this but if not it could save you a minute — first
there's a 401 because of the Date format, using `http_date` from Django
utils fixes that.

After that it's crypto signature stuff, so I hope that's the part you know!!

**Comment by mouse-reeve** [comment]
thank you! I think I also used the wrong inbox fragment -- it should be the destination inbox not the current user's inbox
