### ISSUE TITLE
Have a concept of place within a book

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/fedireads#101]
Page number, chapter, section, line number.....? Needs to have a sense of what units a text breaks down into, and what numerical range exists. I'm not sure where this data can reliably come from.

Relevant to #98 #99 #56

**Comment by mouse-reeve** [comment]
having looked more at the edition data, pages is the only thing that's available, but the coverage, I think, is pretty good.

**Comment by wizzwizz4** [comment]
Books published in non-printed formats (e.g. audiobooks, ebooks) don't have pages. It would be nice to be able to specify chapters, seconds, words etc. where that information is available.

**Comment by mouse-reeve** [comment]
Agreed! Unfortunately right now, only pages are available, so the alternative in to use percent. I'll keep an eye out for sources of data on chapter and duration, though

**Comment by wizzwizz4** [comment]
BookWyrm users are potential sources of that data. Not particularly authoritative ones, but Wikipedia and OpenStreetMap suggest that that isn't much of a problem.
