### ISSUE TITLE
Reviews without ratings

### ISSUE THREAD

**Issue by cthulahoops** [mouse-reeve/fedireads#121]
Should it be possible to write a review without providing a numeric rating? If so, should we allow zero star rating, or start the star rating at 1? (The ui could get confusing if we have to distinguish between zero and no rating.)

Looking at my goodreads export, it looks like books I haven't rated show as zero. (I'm hope I'm not accidentally pulling down the average on books just because I didn't rate them.)

**Comment by cthulahoops** [comment]
Likewise ratings without reviews.

**Comment by mouse-reeve** [comment]
I intended 0 stars to mean "not rated," I just didn't catch the UI up with that (so they bring down averages currently, although they shouldn't).  I believe that's what goodreads does too! And I do think you should be able to leave both reviews without ratings and ratings without reviews.

**Comment by cthulahoops** [comment]
Awesome! I suggest we use nulls to represent no rating, then the average will just work. (I think.)

**Comment by mouse-reeve** [comment]
having looked at rating-without-review, I'm starting to think it should be a separate table. `name` is a required field on `Review`, and I feel like without that, the validation and activitypub serialization is going to get gnarly.

**Comment by cthulahoops** [comment]
I thought about that, but I think where both exist there's a strong link between the rating and review: they'll be displayed together, be a single activity, it's the rating for the review... The same table with nullable fields seems sensible.

Is there anything stopping the activitypub fields being optional?

Otherwise, I guess it's two tables, and separate Review and Rating statuses.

**Comment by mouse-reeve** [comment]
I think if the fields are optional, it could lead to display problems across different platforms. But maybe the best solution is just to serialize ratings-only activities differently...

**Comment by cthulahoops** [comment]
That makes sense, and we can easily tweak the serialisation to deal with any problems.
