### ISSUE TITLE
mastodon delete user activities fail to verify

### ISSUE THREAD

**Issue by mouse-reeve** [mouse-reeve/fedireads#166]
The user is gone, so I can't load their public key, so the authentication always fails, and then the server keeps trying to  re-send me the delete activity and I just keep responding with a 401

**Comment by cthulahoops** [comment]
Is this between two fedireads instances or fedireads & mastodon?

**Comment by mouse-reeve** [comment]
fedireads and mastodon.

**Comment by cthulahoops** [comment]
This is an interesting one!

Either we have the account in our db and can use the public key we already hold, or we don't, in which case the delete activity is a no-op anyway and we can safely discard it.

We need to: use the cached version of the public key to verify the message, and (perhaps?) have a special case to give a nicer http response for deletes of users that don't exist so we don't keep getting the resend. (I guess we could just wait for the remote to give up.)

Related issue in mastodon: https://github.com/tootsuite/mastodon/issues/10286

**Comment by mouse-reeve** [comment]
interesting! I think it would be most internally consistent with what's already there to respond with a 404 in the case that the user isn't in the database? But I don't recall off the top of my head if that would satisfy the sender to not keep re-trying (I think it would?)

**Comment by cthulahoops** [comment]
Does that imply that the inbox doesn't exist (which it probably does)? That said we raise 404 for unrecognised activities too.

Btw, I'm now working on improving / testing the signature code.

**Comment by mouse-reeve** [comment]
oh that's a good point. I'm not sure that we SHOULD be raising 404s, just that we are. I'd be interested to know what mastodon does in these cases (but don't have time to figure it out just now).
