### ISSUE TITLE
possible to follow a user multiple times?

### ISSUE THREAD

**Issue by mewo2** [mouse-reeve/fedireads#47]
Looks like I have multiple followers who are all the same user?
<img width="321" alt="Screen Shot 2020-02-19 at 21 34 37" src="https://user-images.githubusercontent.com/360952/74878911-012e5180-5360-11ea-9268-3f6f1f66e0c9.png">

**Comment by mouse-reeve** [comment]
this is probably a problem with the uniqueness constraint on the UserRelationship table, and also the app should send 302 (or whatever the right code is) responses to duplicate incoming requests

**Comment by mouse-reeve** [comment]
this should be fixed
