### ISSUE TITLE
Stumbled upon error - 'dict' object has no attribute 'split'

### ISSUE THREAD

**Issue by ThatOneBab** [mouse-reeve/fedireads#52]
https://fedireads-test.glitch.me/author/OL250132A

![image](https://user-images.githubusercontent.com/55556971/74890035-cffa5500-5350-11ea-849c-b9ee4acba907.png)

Not sure what else to add here, but the author was supposed to be "Gerd Brantenberg". A misspelled version of the same author's name ("Gerd Brandenberg") also exists and is fine, however.

**Comment by mouse-reeve** [comment]
good catch! fix is probably related to #51 and a general overhaul of error handling in OL data.

You can correct the author name on openlibrary.org: https://openlibrary.org/authors/OL250132A/Gerd_Brantenberg
