### ISSUE TITLE
Invalid OpenLibrary work ID

### ISSUE THREAD

**Issue by tuskpot** [mouse-reeve/fedireads#63]
I found a book that shows up in the search results, but clicking on it throws an "Invalid OpenLibrary work ID" exception.

Search for "legend of biel":
http://fedireads-test.glitch.me/search/?q=legend+of+biel

Click on the 1976 copy:
http://fedireads-test.glitch.me/book/OL7525410M

In case the error goes away by itself, this is the error I got:
http://dpaste.com/302FJ33

**Comment by mouse-reeve** [comment]
Thank you! It looks like search turned up an edition when I was only expecting works
